version: '3.8'

services:
  backend:
    build:
      context: ./Horizon.Server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__PostgresConnection=${ConnectionStrings__PostgresConnection}
    networks:
      - coolify
    volumes:
      - app_data:/app/data

  frontend:
    build:
      context: ./horizon.client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - coolify

networks:
  coolify:
    external: true

volumes:
  app_data: