using Horizon.Server.Modules.Shared.Domain.Common;

namespace Horizon.Server.Modules.Users.Domain.Entities;

/// <summary>
/// Represents a user role (e.g. Admin, HRManager, DepartmentManager, Employee).
/// Roles control which authorization policies and permission claims are included
/// in the JWT access token generated by <c>JwtTokenGenerator</c>.
/// </summary>
public class Role : BaseEntity, IReferenceEntity
{
    /// <summary>EF Core parameterless constructor — not for direct use.</summary>
    private Role() { }

    /// <summary>
    /// Creates a new role.
    /// </summary>
    /// <param name="code">Short unique business code (e.g. "Admin", "Employee").</param>
    /// <param name="name">Human-readable display name.</param>
    /// <param name="description">Optional description of what the role allows.</param>
    /// <param name="sortOrder">Position in ordered lists.</param>
    /// <param name="createdBy">ID of the actor who created this role.</param>
    public Role(string code, string name, string? description, int sortOrder, int createdBy) : base(createdBy)
    {
        Code = code;
        Name = name;
        Description = description;
        SortOrder = sortOrder;
    }

    /// <summary>Gets the unique business code used in authorization policies and JWT claims.</summary>
    public string Code { get; private set; } = null!;

    /// <summary>Gets the display name shown in the UI.</summary>
    public string Name { get; private set; } = null!;

    /// <summary>Gets the optional description of the role's permissions.</summary>
    public string? Description { get; private set; }

    /// <summary>Gets the display sort order.</summary>
    public int SortOrder { get; private set; }

    private readonly List<User> _users = new();
    /// <summary>Gets all users currently assigned this role.</summary>
    public virtual IReadOnlyCollection<User> Users => _users.AsReadOnly();

    private readonly List<ApprovalStage> _approvalStages = new();
    /// <summary>Gets the approval-template stages that require this role's approval.</summary>
    public virtual IReadOnlyCollection<ApprovalStage> ApprovalStages => _approvalStages.AsReadOnly();
}
